-- Seeds ~50 Philippine emergency hotlines/hospitals into the phonebook app.
-- Run AFTER you've registered your first account (assumes that account has id = 1).
-- If your account has a different id, change the 1 below to your user id.
USE phonebook_db;

INSERT INTO contacts (user_id, name, phone, email, address, notes) VALUES
(1, 'National Emergency Hotline', '911', 'info@911.gov.ph', '', 'Main national emergency hotline for police, fire, and medical assistance.'),
(1, 'NDRRMC (Disaster Response)', '(02) 8911-1406', 'opcen@ndrrmc.gov.ph', '', 'National Disaster Risk Reduction and Management Council.'),
(1, 'PNP - National Police', '117', 'feedback@pnp.gov.ph', '', 'Philippine National Police emergency hotline.'),
(1, 'BFP - Bureau of Fire Protection', '(02) 8426-0219', 'ofc@bfp.gov.ph', '', 'National fire emergency response and rescue services.'),
(1, 'Philippine Red Cross', '143', 'communication@redcross.org.ph', '', 'Blood coordination, disaster rescue, and ambulance services.'),
(1, 'MMDA (Metro Manila Dev Auth)', '136', 'pmo@mmda.gov.ph', '', 'Traffic updates, road emergencies, and flood monitoring.'),
(1, 'DOH - Dept of Health', '(02) 8651-7800', 'callcenter@doh.gov.ph', '', 'Health emergencies and national hospital coordination.'),
(1, 'PCG - Philippine Coast Guard', '(02) 8527-3877', 'pcg@coastguard.gov.ph', '', 'Maritime search and rescue, sea-based emergencies.'),
(1, 'Philippine General Hospital (PGH)', '(02) 8554-8400', 'pgh@up.edu.ph', '', 'Major public referral hospital located in Manila.'),
(1, 'St. Luke Medical Center - QC', '(02) 8723-0101', 'info.qc@stluke.com.ph', '', 'Emergency room and trauma center - Quezon City.'),
(1, 'St. Luke Medical Center - BGC', '(02) 8789-7700', 'info.bgc@stluke.com.ph', '', 'Emergency room and trauma center - Global City.'),
(1, 'Makati Medical Center', '(02) 8888-8999', 'mmc@makatimed.net.ph', '', 'Emergency and trauma services in Makati.'),
(1, 'The Medical City - Pasig', '(02) 8988-1000', 'mail@themedicalcity.com', '', 'Main hospital hotline and emergency services.'),
(1, 'Lung Center of the Philippines', '(02) 8924-6101', 'lcp@lungcenter.gov.ph', '', 'Specialized respiratory and emergency medical facility.'),
(1, 'National Kidney & Transplant Inst', '(02) 8981-0300', 'info@nkti.gov.ph', '', 'Specialized renal and emergency care.'),
(1, 'Philippine Heart Center', '(02) 8925-2401', 'director@phc.gov.ph', '', 'Cardiovascular emergency care and surgery.'),
(1, 'East Avenue Medical Center', '(02) 8928-0611', 'eamc@doh.gov.ph', '', 'Public trauma and general emergency hospital.'),
(1, 'San Lazaro Hospital', '(02) 8732-3776', 'slh@doh.gov.ph', '', 'Specialized infectious disease emergency hospital.'),
(1, 'Amang Rodriguez Memorial Center', '(02) 8941-5854', 'armmc@doh.gov.ph', '', 'Public emergency hospital serving Marikina/Rizal.'),
(1, 'Rizal Medical Center', '(02) 8865-8400', 'rmc@doh.gov.ph', '', 'Public emergency hospital serving Pasig/Rizal.'),
(1, 'PNP Anti-Kidnapping Group', '(02) 8724-7329', 'akg@pnp.gov.ph', '', 'Specialized police unit for kidnapping emergencies.'),
(1, 'PNP Highway Patrol Group', '(02) 8723-0401', 'hpg@pnp.gov.ph', '', 'Highway accidents, carnapping, and road security.'),
(1, 'NBI - National Bureau of Investigation', '(02) 8523-8231', 'crmd@nbi.gov.ph', '', 'Investigative assistance and major crime reporting.'),
(1, 'PAGASA (Weather Bureau)', '(02) 8284-0800', 'information@pagasa.dost.gov.ph', '', 'Typhoon tracking, weather warnings, and flood alerts.'),
(1, 'PHIVOLCS (Earthquake/Volcano)', '(02) 8426-1468', 'phivolcs_opcen@phivolcs.dost.gov.ph', '', 'Earthquake monitoring and volcanic eruption alerts.'),
(1, 'DSWD (Social Welfare)', '(02) 8931-8101', 'osec@dswd.gov.ph', '', 'Disaster relief distribution and social services emergency.'),
(1, 'Meralco (Power Outages/Hazards)', '16211', 'customercare@meralco.com.ph', '', 'Electrical fires, downed wires, and power emergencies.'),
(1, 'Maynilad Water (Water Emergencies)', '1626', 'customer.care@mayniladwater.com.ph', '', 'Major water leaks, pipe bursts, and supply issues.'),
(1, 'Manila Water Hotline', '1627', 'customer@manilawater.com.ph', '', 'Water line ruptures and critical supply emergencies.'),
(1, 'QC Action Center', '122', 'qchelpline@quezoncity.gov.ph', '', 'Local city government emergencies in Quezon City.'),
(1, 'Manila City Hall Action Center', '(02) 8527-4950', 'manila_help@manila.gov.ph', '', 'Local city government emergencies in Manila City.'),
(1, 'Pasig City Emergency Unit (RED)', '(02) 8643-0000', 'pasigred@pasig.gov.ph', '', 'Pasig City local rescue and disaster team.'),
(1, 'Makati Rescue', '(02) 816-8000', 'makati_rescue@makati.gov.ph', '', 'Makati City local rescue and medical dispatch.'),
(1, 'Taguig City Emergency Hotline', '(02) 8628-0000', 'taguigrescue@taguig.gov.ph', '', 'Taguig Command Center for emergencies and rescue.'),
(1, 'Mandaluyong Rescue', '(02) 8533-2225', 'mandaluyong_rescue@mandaluyong.gov.ph', '', 'Local disaster response for Mandaluyong.'),
(1, 'Marikina Rescue', '161', 'marikina_rescue@marikina.gov.ph', '', 'Marikina City swift flood and medical rescue.'),
(1, 'Parañaque Cleanliness & Rescue', '(02) 8820-7383', 'pque_rescue@paranaque.gov.ph', '', 'Parañaque City disaster and medical response.'),
(1, 'Las Piñas Emergency Command', '(02) 8552-8224', 'lp_rescue@laspinas.gov.ph', '', 'Local command center for Las Piñas.'),
(1, 'Pasay City Police Station', '(02) 8831-1544', 'pasay_police@pnp.gov.ph', '', 'Local police response for Pasay City.'),
(1, 'Caloocan Rescue Team', '(02) 8888-2256', 'caloocan_rescue@caloocan.gov.ph', '', 'Disaster and medical emergencies in Caloocan.'),
(1, 'Malabon City Disaster Command', '(02) 8921-6009', 'malabon_mdrrmo@malabon.gov.ph', '', 'Flood and rescue updates for Malabon.'),
(1, 'Navotas Rescue Center', '(02) 8281-8531', 'navotas_rescue@navotas.gov.ph', '', 'Coastal and local emergencies in Navotas.'),
(1, 'Valenzuela Alert Center', '(02) 8352-5000', 'alert@valenzuela.gov.ph', '', 'Unified command center for Valenzuela City.'),
(1, 'San Juan City Emergency Command', '(02) 8723-9541', 'sanjuan_rescue@sanjuan.gov.ph', '', 'Local police, fire, and medical dispatch for San Juan.'),
(1, 'Muntinlupa Rescue', '(02) 8925-4351', 'muntinlupa_rrmo@muntinlupa.gov.ph', '', 'Disaster response team for Muntinlupa City.'),
(1, 'Pateros Rescue Team', '(02) 8642-5159', 'pateros_rescue@pateros.gov.ph', '', 'Local emergency response for Pateros municipality.'),
(1, 'Chinese General Hospital', '(02) 8711-4141', 'info@cghmc.com.ph', '', 'Emergency room and medical services in Manila.'),
(1, 'Capitol Medical Center', '(02) 8372-3826', 'info@capitolmed.com.ph', '', 'Emergency medical and trauma department in QC.'),
(1, 'Our Lady of Lourdes Hospital', '(02) 8716-8001', 'ollh@ollh.com.ph', '', 'Emergency medical facility located in Sta. Mesa.'),
(1, 'Chong Hua Hospital (Cebu City)', '(032) 255-8000', 'info@chonghua.com.ph', '', 'Primary emergency and critical care hospital in Cebu.');